{
 "title": "Credit API Monitoring",
 "tags": [
  "ml",
  "credit-scoring",
  "api"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "requests/sec"
    }
   ]
  },
  {
   "title": "Inference Latency (p95)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(model_inference_latency_seconds_bucket[1m]))",
     "legendFormat": "p95 latency"
    }
   ]
  },
  {
   "title": "HTTP Error Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m]))",
     "legendFormat": "5xx errors/sec"
    }
   ]
  }
 ]
}